### PR TITLE
DBT-784 Fix-1.8.0-impala Support dbt-core 1.8.0 for dbt-impala

### PR DESCRIPTION
**Pull request by niranjancdw**
## Describe your changes
Upgraded dbt-impala's dbt-core dependency to 1.8.0.

## Internal Jira ticket number or external issue link
https://jira.cloudera.com/browse/DBT-784

## Testing procedure/screenshots(if appropriate):
Test gist on all python versions

https://gist.github.com/niranjancdw/6d0f0ee196a8e90890194f90882d4780

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have formatted my added/modified code to follow pep-8 standards
- [X] I have checked suggestions from python linter to make sure code is of good quality.

### CODE REVIEW

**Comment by niteshy** [comment]
LGTM, just run the tests for all python versions.

**Comment by niranjancdw** [comment]
> https://gist.github.com/niranjancdw/7b2a4dac0c6d5165611defda3b73cee6

Hi @niteshy 

Tests passed on all python versions, there seem to be 2 intermittent failures probably because of network glitch but they passed on rerun. 

https://gist.github.com/niranjancdw/d0c8dc2dd6093fd78621e9fbf1d4a393

**Review by niteshy — APPROVED** [review]
LGTM

**Comment by ksirmons** [comment]
Is there a timeline for when the pip packages will be updated to support this update?

https://pypi.org/project/dbt-impala/

Keith

**Comment by niranjancdw** [comment]
Hi Keith, 

We are planning to do the release by this week. Thanks for following up and offering help. I'll let you know once the release is done. 

Regards,
Niranjan

**Comment by niranjancdw** [comment]
Hello @ksirmons 

PyPi has been updated with 1.8.0 version of the adapter. 

Regards,
Niranjan

**Comment by ksirmons** [comment]
> Hello @ksirmons
> 
> PyPi has been updated with 1.8.0 version of the adapter.
> 
> Regards, Niranjan

Thank you for the notification.
Upgraded the package today and after some errors it all appears to be working well.

I did a simple upgrade

`pip install dbt-impala --upgrade`

after pip upgraded dbt-impala and dbt-core I ran dbt --version and received an error message
`dbt No module named 'dbt.adapters.factory'`

Found this thread: https://github.com/dbt-labs/dbt-core/issues/10135

I then forced reinstalled dbt-adapters
`pip install --force-reinstall dbt-adapters`

which threw some version combability issues.

```
pip install --force-reinstall dbt-adapters==1.7.0
pip install --force-reinstall dbt-common==1.10.0
```

Force reinstalling to those versions got my environment back working with this set of dbt pip versions:
```
dbt-adapters==1.7.0
dbt-common==1.10.0
dbt-core==1.8.8
dbt-extractor==0.5.1
dbt-impala==1.8.0
```

**Comment by niranjancdw** [comment]
Hi @ksirmons 

Thanks for the feedback, good to know that upgrade went fine for you. 

Regards,
Niranjan

**Pull request merged**
