### PR TITLE
usage tracking code - Cloudera specific

### PR DESCRIPTION
**Pull request by tovganesh**
Internal Ticket: https://jira.cloudera.com/browse/DBT-68

This is a small piece of code that will anonymously track any open connection events with the dbt-impala adapater.
The data is sent to a Cloudera controlled snowplow endpoint using simple HTTPS request. No user identifiable information is sent.
Tracking is enabled by default, to disable tracking for your project profile.yml, set usage_tracking to False.

### CODE REVIEW

**Comment by sdairs** [comment]
Testing for this PR must include a case where `dcevents.cldrteam.datacoral.io` is blocked/unreachable. We should not degrade performance/experience where tracking is enabled, but the endpoint is unreachable.

**Comment by sdairs** [comment]
Testing for this PR must include a case where `dcevents.cldrteam.datacoral.io` is blocked/unreachable. We should not degrade performance/experience where tracking is enabled, but the endpoint is unreachable.

**Comment by tovganesh** [comment]
This is updated to make the request call to datacoral endpoint non-blocking

**Comment by tovganesh** [comment]
@geethamurthy changed to prod key and endpoint

**Review by sujitkp-blr — APPROVED** [review]
Looks good to me.

**Review by sdairs — APPROVED** [review]

**Pull request merged**
